INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('POULET FERM,ARGOAT 1,6/1,7K LR', 'kg', 8.03, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PINTADE FERM,NORMA,1,2/1,4K LR', 'kg', 9.24, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PINTADE BOURGOGNE 1,2/1,4KG LR', 'kg', 9.69, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SUPREME PINT,BOUR,180/240X4 LR', 'kg', 20.53, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CAILLE CHALLANS 225G IGP LR', 'kg', 15.69, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CANARD PAC NU 2,9KG', 'kg', 10.27, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT,CANARD A/PEAU 460G X2', 'kg', 22.01, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE DE CANARD 350G X2', 'kg', 13.27, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SAUTE CANARD S/OS S/P X2,5KG', 'kg', 20.55, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SAUTE CANARD S/OS A/P 2,5KG', 'kg', 16.34, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT, CANETTE 190G X2', 'kg', 25.71, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE DE CANETTE 180G X2', 'kg', 13.36, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CANETTE PAC NUE 1,5KG', 'kg', 11.04, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PLT FERMIER JNE 1.4/1.6 KG LR', 'kg', 6.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('POULET FERMIER NU 1,5/1,7KG LR', 'kg', 7.21, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET FERMIER PAC 1.2/1.4K LR', 'kg', 7.27, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE DINDE FEMEL,2PCE 1K4 LR', 'kg', 7.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('POULET FERMIER BLC 1,6/1,8K LR', 'kg', 8.38, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET FERM,LR BLANC 1,3/1,5K', 'kg', 8.38, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PLT FERMIER JAUNE LR 1,4/1,6KG', 'kg', 8.36, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUIS.PLT.FERM.LR BOURG.S/V X10', 'kg', 9.25, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PINTADE FERM,MAIN,PAC NU 1K2LR', 'kg', 9.78, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('DINDE FERMIERE LOUE 3.75KG LR', 'kg', 13.56, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('EMINCE HAUT CUISSE DDE 2,5K LR', 'kg', 14.52, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE DINDE 50/70G 2,5 KG LR', 'kg', 14.68, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MORCEAUX FLT DDE 40/60G 2K5 LR', 'kg', 15.65, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT DINDE S/P 2PCES 1,5 KG LR', 'kg', 15.29, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SOT L''Y LAISSE DINDE 1 KG LR', 'kg', 16.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ESCAL.DINDE 130/150G X10 LR', 'kg', 16.68, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ROTI FLT DINDE S/B 1,8/2,2K LR', 'kg', 17.24, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT POULET GASCOGNE LR 160GX10', 'kg', 19.88, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SUPREME PINTADE S/ATX4 770G LR', 'kg', 21.03, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT,PLT,FERM,LR 120/150GX6', 'kg', 23.24, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('POULET FERMIER NU 1,5KG *BIO', 'kg', 10.38, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EMINCES CUISSE PLT SP 2K5*BIO', 'kg', 21.67, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE POULET FERM,SO 2,5K *BIO', 'kg', 21.67, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EMINCE CUISS,PLT FERM, 1KG*BIO', 'kg', 22.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT POULET FERMIER 720GX4 *BIO', 'kg', 32.36, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULE CL, A PAC NUE 1,1/1,2 KG', 'kg', 4.85, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COQUELET PAC NU 500/650 G', 'kg', 8.82, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('MCX COQ S/COLONNE NU 200/250G', 'kg', 8.72, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PINTADE CLASSE A PAC NUE 1,2KG', 'kg', 7.67, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE PINTAD,DEJ,180/220G X10', 'kg', 10.85, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE PINTAD,DEJ,150/180G X10', 'kg', 10.85, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SUPREME PINTADE 180/220G X10', 'kg', 17.11, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CARCASSE POULET VRAC 5 KG', 'kg', 3.75, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE PLT A/DOS 240/260GX10X2', 'kg', 4.98, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('AILE POULET 2,5KG', 'kg', 5.24, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUIS POULET A/DOS 220/240G X10', 'kg', 5.31, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET A PAC NU S/T.BLANC 1.2K', 'kg', 5.49, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('POULET BLANC PAC NU A S/T 1KG', 'kg', 5.49, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('HAUT CUIS, POULET 130/160G X20', 'kg', 5.69, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PILON DE POULET NU 80/120G', 'kg', 5.69, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE PLT DEJ,180/200G X10', 'kg', 5.8, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('POULET A PAC NU S/T BLANC 1,4K', 'kg', 5.79, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE PLT DEJ 200/220G X10', 'kg', 5.8, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE PLT,DEJ,220/240G X10', 'kg', 6.27, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUIS,PLT,S/OS AP SNACK 1,5KX10', 'kg', 9.89, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE PLT FERMIER 200/240GX10', 'kg', 9.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE PLT S/O S/P 50/70G 2,5KG', 'kg', 10.12, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('EMINCE CUISSE PLT S/OS SP 1 KG', 'kg', 10.55, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT.POULET S/P.120/140GX10', 'kg', 10.59, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SUPREME POULET 200/240G X10', 'kg', 10.6, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT,POULET S/OS S/P 90/120GX10', 'kg', 10.59, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SUPREME POULET 160/200 G X10', 'kg', 10.94, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT. POULET S/AT 2 KG', 'kg', 11.11, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('AIGUIL,POULET 1KG', 'kg', 11.18, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('AIGUIL,POULET THYM/CIT,SV 2,5K', 'kg', 11.81, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ESCAL,PLT JAUNE 130/150 G X10', 'kg', 11.72, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SUPREME PLT JAUNE 200/240G X10', 'kg', 11.94, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE PLT P,CHAMPS 2,5KG', 'kg', 16.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('POULET NU BRESSE AOP 1,8/2,2KG', 'kg', 18.11, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET BRESSE NU 1,4/1,5KG AOP', 'kg', 21.16, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EMINCE EPAUL,DDE S/P S/O 2,5KG', 'kg', 7.93, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CORDON BLEU VOLAILLE 100GX10', 'kg', 9.2, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('EMINCE CUISSE DINDE S/P 2,5 KG', 'kg', 9.31, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('OSSO BUCCO DINDE 100/120G X10', 'kg', 7.8, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ROTI DINDE MIXTE 1,8/2,2 KG', 'kg', 10.12, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ESCAL,DINDE 110/130G X10', 'kg', 11.37, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('EMINCE FILET DINDE 2,5KG', 'kg', 11.26, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ROTI FLT DINDE S/B 1,8/2,2K', 'kg', 11.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE DINDE FEMELLE X2 1,455K', 'kg', 7.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ESCAL,DINDE 130/150G X10', 'kg', 11.36, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ESCAL,DINDE 90/110G X10', 'kg', 11.37, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('EMINCE HAUT CUISSE DINDE 2,5KG', 'kg', 9.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT,DINDE S/P 1,5/1,9KG', 'kg', 10.38, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE DINDE 50/70G 2,5KG', 'kg', 9.35, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE DINDE 70/90G 2,5KG', 'kg', 9.07, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PIGEONNEAU ROYAL NU 540/600 G', 'kg', 22.43, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE CANARD S/O,40/60G 2,5 KG', 'kg', 18.26, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EFFILOCHE CANARD CONFIT 2KG', 'kg', 45.08, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUIS,CANET, A/PEAU 150/200GX15', 'kg', 10.05, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE CANET,A/PEAU 150/200GX2', 'kg', 10.05, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MANCHON CANARD X6 900 G', 'kg', 6.83, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ANDOUILLET, CANARD 110/140GX10', 'kg', 15.24, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET CANARD AP 250/300G X2', 'kg', 15.74, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT,CANETTE A/PEAU 200/250G X2', 'kg', 17.22, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT,CANETTE A/PEAU 170/200GX15', 'kg', 17.22, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE CANETTE DOMBES 200 G X2', 'kg', 15.49, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE CANETTE 150/200G NUE', 'kg', 9.89, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('FILET CANETTE DOMBE 200G X2', 'kg', 21.69, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CANETTE BARBARIE 1,3/1,7K', 'kg', 8.96, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('RABLE LAPIN DESOS,250/300GX5', 'kg', 19.78, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('RABLE LAPIN MCX S/OS 2,5KG', 'kg', 21.67, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('LAPIN ENTIER NU +1,4KG', 'kg', 9.89, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('EMINCE LAPIN S/PEAU S/V 1KG', 'kg', 20.29, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE LAPIN NU 180/220G', 'kg', 17.76, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('RABLE DE LAPIN NU 350 G BBC', 'kg', 17.32, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('RABLE LAPIN NU 300/400G', 'kg', 16.23, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('AIGUILLET,PLT,CORN FLAKES X1KG', 'kg', 14.32, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('NUGGETS VOLAILLE S/ATM 20G X50', 'kg', 8.68, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('AIGUIL,POULET ROTIE 2KG', 'kg', 18.02, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PAUPIETT DINDE S/F 130/150GX10', 'kg', 14.12, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUCISSE VOLAILLE S/ATM 50GX20', 'kg', 11.29, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FOIE VOLAILLE 1KG', 'kg', 4.77, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('GESIER VOLAILLE S/V 1KG', 'kg', 4.83, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('HACHE VOLAILLE AU COUTEAU 1 KG', 'kg', 11.86, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('KNACK VOLAILLE CUITE 1,2KG HAL', 'kg', 10.12, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('AIGUIL, POULET 2,5 KG HALAL', 'kg', 11.14, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET BLC QRT,ARR, 10KG HALAL', 'kg', 4.98, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT,PLT SP HALAL 120/140GX2,5K', 'kg', 11.02, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FILET POULET S/PEAU HALAL 2,5K', 'kg', 11.02, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF MACREUSE/TT/TG CUIT SV 2,2KG', 'kg', 19.36, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF PALERON CUIT BRAISE SV 2,2KG', 'kg', 18.04, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K PALERON DE BŒUF CONFIT CUIT SV 2KG (dans la graisse de canard)', 'kg', 18.3, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K PALERON DE VEAU CONFIT CUIT SV 1KG (dans la graisse de canard)', 'kg', 19.0, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K PALERON DE VEAU CONFIT CUIT SV 1KG CONGELE', 'kg', 20.89, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE PORC FILET CUIT SV 2,2KG', 'kg', 10.16, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ECHINE DE PORC CONFITE CUITE SV 2KG CONGELE', 'kg', 11.66, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE DINDE FILET CUIT SV 2,2KG', 'kg', 16.02, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE DE VEAU 35G CUIT CONGELE', 'kg', 20.75, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SAUTE DE PORC 35G CUIT CONGELE', 'kg', 11.85, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K FAUX FILET FACON TATAKI VBF 200G PRECUIT MARINE CONGELE', 'kg', 32.1, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K TRANCHE ROTI BŒUF CUIT 20G CONGELE IQF', 'kg', 19.95, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K SOURIS D''AGNEAU CUITE 350g/550G x 1', 'kg', 19.16, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K JARRET DE PORC A LA FLEUR DE BIERE CUIT 380/600G', 'kg', 9.2, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K CHILI CON CARNE CUIT 300G SOUS VIDE CONGELE', 'kg', 13.68, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF JUMEAU CUIT SV 1,4KG', 'kg', 18.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('K FONDANT DE VEAU CUIT (au Pineau des Charentes) SV 1,2KG', 'kg', 18.45, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K NOIX DE JOUE DE BŒUF CUITE CONFITE SV 2KG ENV', 'kg', 17.89, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('K FONDANT DE VEAU CUIT CONFIT SV 1,2KG', 'kg', 17.54, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K NOIX JOUE PORC CUIT CONFIT SV 1KG', 'kg', 13.55, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K EFFILOCHE DE PORC CUIT CONFIT OIGNON-POIVRE 500G SOUS VIDE CONGELE', 'kg', 15.8, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K EFFILOCHE DE PORC CUIT SAVEUR EPICES CAJUN 500G SOUS VIDE FRAIS', 'kg', 14.2, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K BOURGUIGNON BŒUF UE 35G CUIT SV 5KG CONGELE', 'kg', 19.23, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K SAUTE DE VEAU 35G CUIT CONGELE', 'kg', 20.75, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K SAUTE DE PORC 35G CUIT CONGELE', 'kg', 11.85, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF MACREUSE/TT/TG CUIT SV 2,2KG CONGELE', 'pièce', 21.16, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF JUMEAU CUIT SV 1,4KG CONGELE', 'pièce', 19.9, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF PALERON CUIT BRAISE SV 2,2KG CONGELE', 'kg', 19.34, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('K FONDANT DE VEAU CUIT (au Pineau des Charentes) SV 1,2KG CONGELE', 'pièce', 20.77, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE PORC FILET CUIT SV 2,2KG CONGELE', 'kg', 11.35, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K JARRET DE PORC A LA FLEUR DE BIERE CUIT CONGELE', 'kg', 9.95, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE DINDE FILET CUIT SV 2,2KG CONGELE', 'pièce', 17.06, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('FILET BŒUF SP 2,8KG+ VBF', 'kg', 27.09, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BŒUF SP 2,4KG+ VBF', 'kg', 26.48, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BŒUF SP 2KG+ VBF', 'kg', 25.37, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU PAD VBF', 'kg', 21.83, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ENTRECOTE SP 3KG+ VBF', 'kg', 22.64, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CARRE COTE BOEUF DEVERTEBRE VBF', 'kg', 20.37, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('COEUR DE RUMSTEAK PAD VBF', 'kg', 17.94, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FAUX FILET SP 6KG+ VBF', 'kg', 16.93, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COEUR DE TENDE TRANCHE PAD VBF', 'kg', 17.44, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('DESSUS PALETTE PAD VBF SV', 'kg', 16.93, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ROND GITE PAD VBF', 'kg', 17.54, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PALERON SP VBF', 'kg', 16.12, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX BASSE COTE SP 4 FACES VBF', 'kg', 15.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FILET BOEUF SP', 'kg', 26.83, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BOEUF SP', 'kg', 26.23, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BOEUF SP', 'kg', 25.17, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ENTRECOTE SP', 'kg', 19.61, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ENTRECOTE SP', 'kg', 18.75, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CARRE COTE BOEUF DEVERTEBRE', 'kg', 16.12, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FAUX FILET SP', 'kg', 15.82, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET SP', 'kg', 15.21, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET SP', 'kg', 14.71, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU PAD', 'kg', 16.93, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ONGLET BOEUF SP', 'kg', 15.21, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('COEUR DE TENDE TRANCHE PAD', 'kg', 16.12, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COEUR DE RUMSTEAK PAD', 'kg', 15.62, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX BASSE COTE SP 4 FACES', 'kg', 14.81, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BOULE MACREUSE PAD', 'kg', 15.82, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PALERON SP', 'kg', 13.29, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('JARRET BOEUF SANS OS', 'kg', 12.84, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('LANGUE BŒUF', 'kg', 10.82, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FILET MIGNON VEAU SP', 'kg', 29.51, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CARRE VEAU ENTIER AVEC OS', 'kg', 15.42, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CŒUR QUASI VEAU SP', 'kg', 18.24, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PICANHA DE VEAU SP (aiguillette de quasi)', 'kg', 17.54, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ARAIGNEE DE VEAU SP *', 'kg', 15.01, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX VEAU SP', 'kg', 18.14, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX VEAU PATISSIERE SP', 'kg', 15.72, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SOUS NOIX VEAU SP', 'kg', 15.92, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EPAULE VEAU SANS OS SP', 'kg', 14.3, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('BAS CARRE VEAU SANS OS', 'kg', 14.05, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FOIE VEAU ENTIER', 'kg', 17.13, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('TETE VEAU S/OS A/LANGUE A PLAT', 'kg', 10.87, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ROGNON VEAU AVEC GRAISSE', 'kg', 6.02, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('GIGOT AGNEAU SANS OS *', 'kg', 19.15, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('1/2 CARRE PORCELET AVEC OS *', 'kg', 13.5, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('CUISSOT PORCELET SANS OS *', 'kg', 12.64, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EPAULE PORCELET SANS OS *', 'kg', 11.07, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET MIGNON PORC SP *', 'kg', 9.71, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('GRILLADE DE PORC *', 'kg', 8.95, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ARAIGNEE PORC SP *', 'kg', 8.95, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BOEUF SP 2,5KG+*', 'kg', 24.9, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BOEUF SP 2KG+*', 'kg', 22.86, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('COEUR DE RTK PAD', 'kg', 13.61, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ENTRECOTE 3+', 'kg', 16.84, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ENTRECOTE 2,5+', 'kg', 15.68, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POIRE PAD', 'kg', 13.61, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('AIGUILLETTE BARONNE', 'kg', 14.54, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CARRE COTE BF DEVERTEBRE*', 'kg', 15.22, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET 7+', 'kg', 15.01, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET 6+', 'kg', 14.6, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET 5+', 'kg', 13.03, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET 4+', 'kg', 12.57, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PALERON', 'kg', 12.57, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('JARRET BOEUF S/OS', 'kg', 11.43, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('COEUR DE TT PAD 4KG+', 'kg', 14.76, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU PAD', 'kg', 15.34, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX BASSE COTE', 'kg', 13.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ONGLET BOEUF SP*', 'kg', 13.26, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('HAMPE BŒUF PAD', 'kg', 12.32, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('LANGUE BOEUF*', 'kg', 8.76, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('DESSUS PALETTE', 'kg', 14.13, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SOUS NOIX VEAU', 'kg', 17.01, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX VEAU PATISSIERE', 'kg', 14.88, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EPAULE VEAU', 'kg', 13.84, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('BAS CARRE VEAU', 'kg', 13.15, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET MIGNON PORC', 'kg', 7.68, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CŒUR TT SIMMENTAL *', 'kg', 16.03, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CŒUR RTK SIMMENTAL', 'kg', 14.53, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET SIMMENTAL', 'kg', 16.03, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ENTRECOTE SIMMENTAL', 'kg', 22.1, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET SIMMENTAL *', 'kg', 29.32, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU SIMMENTAL', 'kg', 16.14, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('BASSE COTE SIMMENTAL *', 'kg', 14.53, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COEUR DE RTK PAD HALAL', 'kg', 14.08, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ENTRECOTE 2,5+ HALAL', 'kg', 17.82, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FAUX FILET 4+ HALAL', 'kg', 13.72, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU PAD HALAL', 'kg', 15.74, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX BASSE COTE HALAL *', 'kg', 14.41, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BOULE MACREUSE HALAL', 'kg', 13.84, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('JARRET BŒUF S/OS HALAL', 'kg', 11.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FILET DE POULET CRU S/AT 2,5KG *', 'kg', 7.65, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT DE POULET CRU S/AT 2,5KG HALAL *', 'kg', 7.65, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('AIGUILLETTE DE POULET S/AT 8X1KG HALAL*', 'kg', 8.14, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PILON DE POULET 2X3KG HALAL*', 'kg', 4.62, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('VIANDE HT CUISSE S/OS S/PEAU 4X2.5KG HALAL*', 'kg', 6.98, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('ORANGE A JUS 6/7 15KG "RG"', 'kg', 1.19, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON BERGAMOTE CAT I ''"CASTAGNARO" COLIS 2,5 KG CAT I', 'kg', 4.89, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ORANGE NAVEL CAT I CAL 3 / COLIS 8.5 KG', 'kg', 2.19, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON BERGAMOTE "LIMONETTE DE MARRAKECH" CAT I', 'kg', 4.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON 4/5 FILET 1KG CAT 1 IMPORT', 'pièce', 2.59, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON CAVIAR JAUNE BQTE 100G', 'pièce', 15.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON CAVIAR ROSE BQTE 100G', 'pièce', 15.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('BANANE P14 18,5KG CAT 1 IMPORT', 'kg', 1.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('BANANE P20 5KG CAT1 IMPORT', 'kg', 1.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FRAISE GARIGUETTE 800G C.1 France', 'pièce', 16.49, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FRAISE GARIQUETTE 250G C.1 FRANCE', 'pièce', 4.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FRAMBOISE 125G CAT 1', 'pièce', 3.29, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FRAMBOISE 125G CAT 1 driscoll', 'pièce', 3.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('MURE 125G CAT 1', 'pièce', 3.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('GROSEILLE 125G CAT 1', 'pièce', 3.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PASTEQUE FASHION S/P 7,5KG CAL 2', 'kg', 3.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('TOMATE CERISE ALLONGEE CAT1 FR.250G', 'pièce', 2.49, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE COTELEE NOIRE CRIMEE CAT2 FR.3,5KG', 'kg', 5.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE ANANAS COTELEE FR.CAT2 3.5KG', 'kg', 5.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE COTELEE MARMANDE CAT2 FR. 3.5KG', 'kg', 5.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE COCKTAIL GRAPPE CAT1 FR. 3.5KG', 'kg', 6.49, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE CERISE MULTICOLORE CAT1 FR.4KG', 'kg', 6.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('AUBERGINE FILET 1KG', 'kg', 4.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('COURGETTE FILET 1KG', 'kg', 2.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('POIVRON ROUGE 1KG CAT 1 UE', 'kg', 4.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('POIVRON VERT FILET 1KG CAT 1 UE', 'kg', 4.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('POIVRON JAUNE FILET 1KG CAT 1 UE', 'kg', 4.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ASPERGE VIOLETTE 16/22 C.1 France', 'kg', 18.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ASPERGE BLANCHE 500G CAL 16/22 C.1 France', 'kg', 10.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ASPERGE VIOLETTE 16/22 C.1 France', 'kg', 13.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ASPERGE VERTE 16/22 C.1 France', 'kg', 12.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('AIL DES OURS C.1 France', 'kg', 17.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CEBETTE 100G PROVENCE CAT 1', 'kg', 1.46, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CHOU FLEUR CAT 1', 'pièce', 2.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('POIREAU BOTTE 1KG CAT 1', 'kg', 1.59, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('SALADE CRAQUANTE ITALIENNE CAT 1 500g "MARIUS AUDA"', 'kg', 3.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('SALADE MELANGE NICOIS CAT 1500G "MARIUS AUDA"', 'kg', 3.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('SALADE MELANGE BISTROT CAT 1 500G "MARIUS AUDA"', 'kg', 3.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('PDT AGRIA FRITE 10KG CAT 1 France', 'kg', 0.79, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('PDT SIRTEMANOIRMOUTIER France IGP 35/55', 'kg', 9.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FEUILLE CAPUCINE X15PCE', 'kg', 4.51, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLEUR LAVANDE 30G', 'kg', 3.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLEUR PHLOX', 'kg', 3.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLEUR PENSEE/VIOLA', 'kg', 3.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLEUR DE FENOUIL', 'kg', 3.95, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FLEUR MINI BATAILLE', 'kg', 3.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MICRO POUSSE FOLIE DE RADIS France 40G', 'kg', 5.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('MICRO POUSSE CORIANDRE France 30G', 'kg', 5.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MICRO POUSSE POIS VERT France 40G', 'kg', 5.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MICRO POUSSE MELI-MELO France 40G', 'kg', 5.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('MICRO POUSSE MOUTARDE France 40G', 'kg', 5.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MICRO POUSSE RADIS POURPRE France 40G', 'kg', 5.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TRUFFE FRAICHE HIVER 3/4 PIECES CAT 1 100G FR', 'kg', 290.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('TRUFFE FRAICHE HIVER 1/2 PIECES CAT 1 100G FR', 'kg', 290.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('TRUFFE FRAICHE HIVER 8/10 PIECES CAT 1 100G FR', 'kg', 250.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COFFRET TRUFFE HIVER 1P EXTRA 100G + RAPE + BROSSE', 'kg', 149.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FRUIT DE LA PASSION CAT1 1KG', 'kg', 15.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ANANAS B9 CAT2 *BIO', 'kg', 3.49, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BASILIC PETIT POT X6 CAT2 FR.*BIO', 'kg', 1.79, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BATAVIA X12 CAT2 FR.3.6KG *BIO', 'kg', 16.8, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CELERI RAVE FR.X8 8KG CAT2*BIO', 'kg', 2.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CHOU BLANC CAT2 FR.1KG *BIO', 'kg', 2.29, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('MANDARINE 3/4 CAT2 6KG *BIO', 'kg', 2.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CONCOMBRE 3/4 CAT2 *BIO', 'kg', 24.0, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('PDT MAIWEN BROSSEE 40/60 FR.10KG CAT2 *BIO X', 'kg', 1.89, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PERSIL FRISE PETIT POT X6 FR.CAT2 BIO', 'kg', 1.79, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ROMARIN PETIT POT CAT2 FR.(6) *BIO', 'kg', 1.79, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('THYM PETIT POT X6 FR.CAT2 *BIO', 'kg', 1.79, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1.5/1.9 kg', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de saumon sans peau sans arrêtes ASC', 'kg', 24.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('120 g', 'kg', 23.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('150 g', 'kg', 23.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180 g', 'kg', 23.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('90 g', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('120 g', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('150 g', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180 g', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('4/5 kg', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('2/3 kg', 'kg', 14.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Truite entière vidée grattée', 'kg', 12.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Truite portion vidée', 'kg', 11.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 20.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de truite avec peau sans arêtes', 'kg', 12.95, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pavé de truite avec peau', 'kg', 26.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Huître Marennes Oléron n°2 IGP', 'kg', 42.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Huître Marennes Oléron n°3 IGP', 'kg', 36.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Huître Marennes Oléron n°3 IGP', 'kg', 66.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de dorade', 'kg', 28.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 16.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 18.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/180 g', 'kg', 32.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/220 g', 'kg', 37.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 15.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 17.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('800g/1 kg', 'kg', 19.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1/1,5 kg', 'kg', 22.2, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de harend doux Label Rouge', 'kg', 15.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de haddock moyen fumé à l''ancienne MSC', 'kg', 36.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Dos cabillaud avec peau', 'kg', 36.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Dos cabillaud sans peau', 'kg', 31.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('300g +', 'kg', 19.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de cabillaud avec peau', 'kg', 26.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de lieu noir sans peau', 'kg', 14.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet merlan papillon', 'kg', 12.2, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet églefin sans peau Ecosse', 'kg', 13.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de lieu jaune avec peau', 'kg', 31.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de lieu noir sans peau', 'kg', 14.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de sardine papillon', 'kg', 9.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Longe de thon fraiche', 'kg', 22.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Longe de thon pour sashimi décongelée', 'kg', 27.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Longe de thon albacore décongelé MSC', 'kg', 26.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Préparation de longe de thon albacore décongelé MSC', 'kg', 26.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Préparation de longe de thon albacore décongelée saumurée MSC', 'kg', 14.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Préparation de longe d''espadon décongelée saumurée', 'kg', 17.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Longe d''Espadon fraiche', 'kg', 21.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Aile de raie pelée 1 face', 'kg', 13.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pièce de 1/2 kg', 'kg', 31.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pièce de 2/3 kg', 'kg', 39.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Bouille roche', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Brochet', 'kg', 16.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Cabillaud VDK 4/6 kg', 'kg', 20.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Merlu 3/4 kg', 'kg', 21.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Lieu jaune 2/4 kg VDK', 'kg', 16.6, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Queue de lotte 2/4 kg', 'kg', 27.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('800/1000 g', 'kg', 32.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('2/3 kg', 'kg', 43.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Sandre 2/4 kg', 'kg', 21.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Sardine bretonne', 'kg', 6.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('300/400 g', 'kg', 41.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/500 g', 'kg', 45.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('500/600 g', 'kg', 45.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('500/600 g', 'kg', 50.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de saumon avec peau TRIM B', 'kg', 14.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 23.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 23.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 18.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 18.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 16.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de Saumon sans peau, sans arêtes, sans flanc TRIM E', 'kg', 16.1, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de saumon Label Rouge', 'kg', 24.95, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de saumon avec peau 1,7/1,9 kg (issu Label Rouge)', 'kg', 24.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de bar avec peau écaillée', 'kg', 23.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de bar avec peau écaillée sans arrêtes', 'kg', 29.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de dorade royale avec peau écaillée', 'kg', 22.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de dorade royale avec peau écaillée sans arêtes', 'kg', 29.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de maigre', 'kg', 32.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de truite avec peau', 'kg', 19.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('300/400 g', 'kg', 14.2, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 16.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 17.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('600/800 g', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,8/2,6 kg', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('2,6/3,5 kg', 'kg', 32.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Bar portefeuille', 'kg', 17.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('300/400 g', 'kg', 14.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 15.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 15.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Dorade royale portefeuille', 'kg', 17.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 13.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('800/1000 g', 'kg', 14.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Maigre', 'kg', 14.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Maigre gratté vidé', 'kg', 18.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Maigre ASC', 'kg', 15.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Maigre BIO', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/500 g', 'kg', 29.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/500G', 'kg', 29.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('500/600 g', 'kg', 29.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('3/4 kg', 'kg', 12.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('5/6 kg', 'kg', 12.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('6/7 kg', 'kg', 12.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('7/8 kg', 'kg', 12.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Saumon entier Label Rouge', 'kg', 15.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Seriole lalandi', 'kg', 29.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1/2 kg', 'kg', 24.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('2/3 kg', 'kg', 32.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('3/4 kg', 'kg', 37.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160 g', 'kg', 50.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 50.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160g', 'kg', 44.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 44.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('60/80 g', 'kg', 25.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('110/130 g', 'kg', 25.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('110/130 g', 'kg', 25.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160 g', 'kg', 22.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 25.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pavé de lieu jaune avec peau gratté', 'kg', 35.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pavé de lotte sans peau', 'kg', 60.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Tronçon de lotte', 'kg', 51.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('140/160g', 'kg', 23.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 29.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160 g', 'kg', 29.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 32.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160g', 'kg', 22.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160 g', 'kg', 22.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 30.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 30.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de dorade royale avec peau ASC', 'kg', 32.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet d''omble chevalier avec peau', 'kg', 36.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pavé de maigre', 'kg', 42.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('80/100 g', 'kg', 20.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('140/160 g', 'kg', 20.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 20.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('80/100 g', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('120 g', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160 g', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pavé de turbot sans peau', 'kg', 115.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Bar entier vidée grattée', 'kg', 14.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Dorade royale vidée grattée', 'kg', 16.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Tronçon de turbot', 'kg', 90.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('60/80 g', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('110/130 g', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160 g', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Anneaux d''encornet décongelées saumurées', 'kg', 15.3, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('Lamelle d''encornet décongelées saumurées', 'kg', 9.99, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('Tentacules de calamar décongelées saumurées', 'kg', 9.9, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('Amandes de mer', 'kg', 4.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Bulot cuit', 'kg', 10.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Corail d''oursin pasteurisé', 'kg', 23.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Coques', 'kg', 10.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Couteau', 'kg', 9.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('20/30', 'kg', 10.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('30/50', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('30/50', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('40/60', 'kg', 8.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('40/60', 'kg', 8.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('60/80', 'kg', 7.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('60/80', 'kg', 7.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Crevette grise moyenne', 'kg', 21.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Crevette grise décortiquée', 'kg', 8.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Crevette grise jumbo', 'kg', 23.95, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Crevette cuite LABEL ROUGE', 'kg', 33.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Chair de tourteaux', 'kg', 75.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Huitre fine normande n°3', 'kg', 30.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Huitre fine normande n°2', 'kg', 35.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 50.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 54.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 62.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 64.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('10/15', 'kg', 29.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('16/20', 'kg', 23.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Bq s/at de 2 kg', 'kg', 3.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Au sac de 10 kg', 'kg', 3.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Moule Hollande PAC BIO', 'kg', 8.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Moule décortiquée', 'kg', 18.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Noix St Jacques avec corail Normande', 'kg', 37.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Noix St jacques avec corail Ecosse', 'kg', 29.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Noix St jacques avec corail Normande', 'kg', 35.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Préparation noix de saint jacques décongelée', 'kg', 55.9, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('Tourteau cuit sous vide', 'pièce', 18.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine de Langoustines', 'kg', 19.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine de Saint-Jacques au muscadet', 'kg', 15.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine de Crabe Armoricaine', 'kg', 26.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine du Pêcheur', 'kg', 14.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine de Homard au Cognac', 'kg', 23.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Cocktail de fruits de mer en saumure', 'kg', 13.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('120 g', 'kg', 9.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Fish and Chips de Colin', 'kg', 12.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de colin meunière', 'kg', 13.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Brandade de morue parmentière', 'kg', 6.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Caviar Oscietre', 'kg', 67.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Caviar Aquitaine Baeri', 'kg', 68.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Poulpe pour carpaccio', 'kg', 70.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Poulpe entier cuit', 'kg', 43.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Tentacule de poulpe cuit', 'kg', 47.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Marinade de pouple', 'kg', 42.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Marinade de calamars', 'kg', 35.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de bonite melva canutera à l''huile d''olive', 'kg', 7.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de Haddock fumé', 'kg', 36.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Chute de haddock fumé', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de hareng doux fumé JC DAVID Label Rouge', 'kg', 4.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filets de hareng fumé', 'kg', 10.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de truite fumé sans arrête tranché machine', 'pièce', 37.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Morue salée', 'kg', 19.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Miettes de morue salée', 'kg', 18.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Miette de surimi', 'kg', 4.1, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Rouleau de surimi SMC', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Jus de moule', 'kg', 5.4, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de 500 g', 'kg', 7.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Tarama blanc', 'kg', 16.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Tarama truffe d''été', 'kg', 11.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de 500 g', 'kg', 11.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de 300g', 'kg', 43.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Œuf de saumon sauvage', 'kg', 13.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Œuf de lompe rouge', 'kg', 5.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Œuf de lompe noir', 'kg', 5.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Œufs de poisson volant wazabi décongelé', 'kg', 8.5, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('Œuf truite', 'kg', 36.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Œuf truite', 'kg', 10.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Œufs de brochet', 'kg', 10.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Poutargue classique sans cire', 'kg', 118.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Poutargue fumée sans cire', 'kg', 119.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de crevettes moyenne en saumure', 'kg', 16.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de crevettes moyenne en saumure', 'kg', 16.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de crevettes grosse en saumure', 'kg', 17.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de chair de crabe ordinaire', 'kg', 14.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de queue d''écrevisses de Louisiane en saumure', 'kg', 30.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Rillettes de maquereau fumé au poivre', 'kg', 4.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Sardines à l''huile d''olive vierge extra BIO millésimées', 'kg', 5.4, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('Saumon fumé ficelle prétranché avec peau', 'kg', 44.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Saumon fumé ficelle Ecosse', 'kg', 40.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Saumon fumé entier Norvège', 'kg', 36.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Saumon fumé tranché machine', 'kg', 30.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Saumon fumé tranché Ecosse', 'kg', 29.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Saumon fumé tranché ASC JC David', 'kg', 44.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Saumon fumé tranché frais ou décongelé', 'pièce', 28.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Thon en morceau à l''huile d''olive', 'kg', 28.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de 780 g', 'kg', 5.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de 780 g', 'kg', 5.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Spaghetti de Mer Frais Salé BIO', 'kg', 17.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Wakamé frais salé BIO', 'kg', 20.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Kombu royal frais salé BIO', 'kg', 17.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Laitue de mer fraiche salée BIO', 'kg', 17.9, 'Transgourmet', 'Produits laitiers', 5, 8, NOW(), NOW()),
('Rameaux de salicornes', 'kg', 8.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Salicorne', 'kg', 15.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Encre de seiche', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Encre de seiche', 'kg', 12.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Blinis gros x4', 'kg', 2.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Blinis minis x16', 'kg', 2.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;
