INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('300g +', 'kg', 19.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de cabillaud avec peau', 'kg', 26.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de lieu noir sans peau', 'kg', 14.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet merlan papillon', 'kg', 12.2, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet églefin sans peau Ecosse', 'kg', 13.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de lieu jaune avec peau', 'kg', 31.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de lieu noir sans peau', 'kg', 14.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de sardine papillon', 'kg', 9.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Longe de thon fraiche', 'kg', 22.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Longe de thon pour sashimi décongelée', 'kg', 27.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Longe de thon albacore décongelé MSC', 'kg', 26.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Préparation de longe de thon albacore décongelé MSC', 'kg', 26.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Préparation de longe de thon albacore décongelée saumurée MSC', 'kg', 14.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Préparation de longe d''espadon décongelée saumurée', 'kg', 17.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Longe d''Espadon fraiche', 'kg', 21.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Aile de raie pelée 1 face', 'kg', 13.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pièce de 1/2 kg', 'kg', 31.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pièce de 2/3 kg', 'kg', 39.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Bouille roche', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Brochet', 'kg', 16.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Cabillaud VDK 4/6 kg', 'kg', 20.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Merlu 3/4 kg', 'kg', 21.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Lieu jaune 2/4 kg VDK', 'kg', 16.6, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Queue de lotte 2/4 kg', 'kg', 27.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('800/1000 g', 'kg', 32.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('2/3 kg', 'kg', 43.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Sandre 2/4 kg', 'kg', 21.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Sardine bretonne', 'kg', 6.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('300/400 g', 'kg', 41.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/500 g', 'kg', 45.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('500/600 g', 'kg', 45.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('500/600 g', 'kg', 50.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de saumon avec peau TRIM B', 'kg', 14.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 23.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 23.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 18.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 18.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1,5/1,9 kg', 'kg', 16.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de Saumon sans peau, sans arêtes, sans flanc TRIM E', 'kg', 16.1, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de saumon Label Rouge', 'kg', 24.95, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de saumon avec peau 1,7/1,9 kg (issu Label Rouge)', 'kg', 24.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de bar avec peau écaillée', 'kg', 23.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de bar avec peau écaillée sans arrêtes', 'kg', 29.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de dorade royale avec peau écaillée', 'kg', 22.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de dorade royale avec peau écaillée sans arêtes', 'kg', 29.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Filet de maigre', 'kg', 32.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de truite avec peau', 'kg', 19.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('300/400 g', 'kg', 14.2, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 16.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 17.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;