INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('K FONDANT DE VEAU CUIT (au Pineau des Charentes) SV 1,2KG CONGELE', 'pièce', 20.77, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE PORC FILET CUIT SV 2,2KG CONGELE', 'kg', 11.35, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K JARRET DE PORC A LA FLEUR DE BIERE CUIT CONGELE', 'kg', 9.95, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE DINDE FILET CUIT SV 2,2KG CONGELE', 'pièce', 17.06, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('FILET BŒUF SP 2,8KG+ VBF', 'kg', 27.09, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BŒUF SP 2,4KG+ VBF', 'kg', 26.48, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BŒUF SP 2KG+ VBF', 'kg', 25.37, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU PAD VBF', 'kg', 21.83, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ENTRECOTE SP 3KG+ VBF', 'kg', 22.64, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CARRE COTE BOEUF DEVERTEBRE VBF', 'kg', 20.37, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('COEUR DE RUMSTEAK PAD VBF', 'kg', 17.94, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FAUX FILET SP 6KG+ VBF', 'kg', 16.93, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COEUR DE TENDE TRANCHE PAD VBF', 'kg', 17.44, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('DESSUS PALETTE PAD VBF SV', 'kg', 16.93, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ROND GITE PAD VBF', 'kg', 17.54, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PALERON SP VBF', 'kg', 16.12, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX BASSE COTE SP 4 FACES VBF', 'kg', 15.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FILET BOEUF SP', 'kg', 26.83, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BOEUF SP', 'kg', 26.23, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BOEUF SP', 'kg', 25.17, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ENTRECOTE SP', 'kg', 19.61, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ENTRECOTE SP', 'kg', 18.75, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CARRE COTE BOEUF DEVERTEBRE', 'kg', 16.12, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FAUX FILET SP', 'kg', 15.82, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET SP', 'kg', 15.21, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET SP', 'kg', 14.71, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU PAD', 'kg', 16.93, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ONGLET BOEUF SP', 'kg', 15.21, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('COEUR DE TENDE TRANCHE PAD', 'kg', 16.12, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COEUR DE RUMSTEAK PAD', 'kg', 15.62, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX BASSE COTE SP 4 FACES', 'kg', 14.81, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BOULE MACREUSE PAD', 'kg', 15.82, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PALERON SP', 'kg', 13.29, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('JARRET BOEUF SANS OS', 'kg', 12.84, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('LANGUE BŒUF', 'kg', 10.82, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FILET MIGNON VEAU SP', 'kg', 29.51, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CARRE VEAU ENTIER AVEC OS', 'kg', 15.42, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CŒUR QUASI VEAU SP', 'kg', 18.24, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PICANHA DE VEAU SP (aiguillette de quasi)', 'kg', 17.54, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ARAIGNEE DE VEAU SP *', 'kg', 15.01, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX VEAU SP', 'kg', 18.14, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX VEAU PATISSIERE SP', 'kg', 15.72, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SOUS NOIX VEAU SP', 'kg', 15.92, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EPAULE VEAU SANS OS SP', 'kg', 14.3, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('BAS CARRE VEAU SANS OS', 'kg', 14.05, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FOIE VEAU ENTIER', 'kg', 17.13, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('TETE VEAU S/OS A/LANGUE A PLAT', 'kg', 10.87, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ROGNON VEAU AVEC GRAISSE', 'kg', 6.02, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('GIGOT AGNEAU SANS OS *', 'kg', 19.15, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('1/2 CARRE PORCELET AVEC OS *', 'kg', 13.5, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;