INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('POULET FERM,ARGOAT 1,6/1,7K LR', 'kg', 8.03, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PINTADE FERM,NORMA,1,2/1,4K LR', 'kg', 9.24, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PINTADE BOURGOGNE 1,2/1,4KG LR', 'kg', 9.69, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SUPREME PINT,BOUR,180/240X4 LR', 'kg', 20.53, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CAILLE CHALLANS 225G IGP LR', 'kg', 15.69, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CANARD PAC NU 2,9KG', 'kg', 10.27, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT,CANARD A/PEAU 460G X2', 'kg', 22.01, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE DE CANARD 350G X2', 'kg', 13.27, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SAUTE CANARD S/OS S/P X2,5KG', 'kg', 20.55, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SAUTE CANARD S/OS A/P 2,5KG', 'kg', 16.34, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT, CANETTE 190G X2', 'kg', 25.71, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE DE CANETTE 180G X2', 'kg', 13.36, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CANETTE PAC NUE 1,5KG', 'kg', 11.04, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PLT FERMIER JNE 1.4/1.6 KG LR', 'kg', 6.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('POULET FERMIER NU 1,5/1,7KG LR', 'kg', 7.21, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET FERMIER PAC 1.2/1.4K LR', 'kg', 7.27, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE DINDE FEMEL,2PCE 1K4 LR', 'kg', 7.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('POULET FERMIER BLC 1,6/1,8K LR', 'kg', 8.38, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET FERM,LR BLANC 1,3/1,5K', 'kg', 8.38, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PLT FERMIER JAUNE LR 1,4/1,6KG', 'kg', 8.36, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUIS.PLT.FERM.LR BOURG.S/V X10', 'kg', 9.25, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PINTADE FERM,MAIN,PAC NU 1K2LR', 'kg', 9.78, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('DINDE FERMIERE LOUE 3.75KG LR', 'kg', 13.56, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('EMINCE HAUT CUISSE DDE 2,5K LR', 'kg', 14.52, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE DINDE 50/70G 2,5 KG LR', 'kg', 14.68, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MORCEAUX FLT DDE 40/60G 2K5 LR', 'kg', 15.65, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT DINDE S/P 2PCES 1,5 KG LR', 'kg', 15.29, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SOT L''Y LAISSE DINDE 1 KG LR', 'kg', 16.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ESCAL.DINDE 130/150G X10 LR', 'kg', 16.68, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ROTI FLT DINDE S/B 1,8/2,2K LR', 'kg', 17.24, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT POULET GASCOGNE LR 160GX10', 'kg', 19.88, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SUPREME PINTADE S/ATX4 770G LR', 'kg', 21.03, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT,PLT,FERM,LR 120/150GX6', 'kg', 23.24, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('POULET FERMIER NU 1,5KG *BIO', 'kg', 10.38, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EMINCES CUISSE PLT SP 2K5*BIO', 'kg', 21.67, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE POULET FERM,SO 2,5K *BIO', 'kg', 21.67, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EMINCE CUISS,PLT FERM, 1KG*BIO', 'kg', 22.62, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLT POULET FERMIER 720GX4 *BIO', 'kg', 32.36, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULE CL, A PAC NUE 1,1/1,2 KG', 'kg', 4.85, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COQUELET PAC NU 500/650 G', 'kg', 8.82, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('MCX COQ S/COLONNE NU 200/250G', 'kg', 8.72, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PINTADE CLASSE A PAC NUE 1,2KG', 'kg', 7.67, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE PINTAD,DEJ,180/220G X10', 'kg', 10.85, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE PINTAD,DEJ,150/180G X10', 'kg', 10.85, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SUPREME PINTADE 180/220G X10', 'kg', 17.11, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CARCASSE POULET VRAC 5 KG', 'kg', 3.75, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUISSE PLT A/DOS 240/260GX10X2', 'kg', 4.98, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('AILE POULET 2,5KG', 'kg', 5.24, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CUIS POULET A/DOS 220/240G X10', 'kg', 5.31, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET A PAC NU S/T.BLANC 1.2K', 'kg', 5.49, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;