INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('CUISSOT PORCELET SANS OS *', 'kg', 12.64, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EPAULE PORCELET SANS OS *', 'kg', 11.07, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET MIGNON PORC SP *', 'kg', 9.71, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('GRILLADE DE PORC *', 'kg', 8.95, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ARAIGNEE PORC SP *', 'kg', 8.95, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BOEUF SP 2,5KG+*', 'kg', 24.9, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET BOEUF SP 2KG+*', 'kg', 22.86, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('COEUR DE RTK PAD', 'kg', 13.61, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ENTRECOTE 3+', 'kg', 16.84, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('ENTRECOTE 2,5+', 'kg', 15.68, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POIRE PAD', 'kg', 13.61, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('AIGUILLETTE BARONNE', 'kg', 14.54, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CARRE COTE BF DEVERTEBRE*', 'kg', 15.22, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET 7+', 'kg', 15.01, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET 6+', 'kg', 14.6, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET 5+', 'kg', 13.03, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET 4+', 'kg', 12.57, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PALERON', 'kg', 12.57, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('JARRET BOEUF S/OS', 'kg', 11.43, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('COEUR DE TT PAD 4KG+', 'kg', 14.76, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU PAD', 'kg', 15.34, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX BASSE COTE', 'kg', 13.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ONGLET BOEUF SP*', 'kg', 13.26, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('HAMPE BŒUF PAD', 'kg', 12.32, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('LANGUE BOEUF*', 'kg', 8.76, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('DESSUS PALETTE', 'kg', 14.13, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SOUS NOIX VEAU', 'kg', 17.01, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX VEAU PATISSIERE', 'kg', 14.88, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('EPAULE VEAU', 'kg', 13.84, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('BAS CARRE VEAU', 'kg', 13.15, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET MIGNON PORC', 'kg', 7.68, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('CŒUR TT SIMMENTAL *', 'kg', 16.03, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CŒUR RTK SIMMENTAL', 'kg', 14.53, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FAUX FILET SIMMENTAL', 'kg', 16.03, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ENTRECOTE SIMMENTAL', 'kg', 22.1, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FILET SIMMENTAL *', 'kg', 29.32, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU SIMMENTAL', 'kg', 16.14, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('BASSE COTE SIMMENTAL *', 'kg', 14.53, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COEUR DE RTK PAD HALAL', 'kg', 14.08, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ENTRECOTE 2,5+ HALAL', 'kg', 17.82, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FAUX FILET 4+ HALAL', 'kg', 13.72, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BAVETTE ALOYAU PAD HALAL', 'kg', 15.74, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('NOIX BASSE COTE HALAL *', 'kg', 14.41, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BOULE MACREUSE HALAL', 'kg', 13.84, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('JARRET BŒUF S/OS HALAL', 'kg', 11.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FILET DE POULET CRU S/AT 2,5KG *', 'kg', 7.65, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT DE POULET CRU S/AT 2,5KG HALAL *', 'kg', 7.65, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('AIGUILLETTE DE POULET S/AT 8X1KG HALAL*', 'kg', 8.14, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PILON DE POULET 2X3KG HALAL*', 'kg', 4.62, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('VIANDE HT CUISSE S/OS S/PEAU 4X2.5KG HALAL*', 'kg', 6.98, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;