INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('FILET CANETTE DOMBE 200G X2', 'kg', 21.69, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CANETTE BARBARIE 1,3/1,7K', 'kg', 8.96, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('RABLE LAPIN DESOS,250/300GX5', 'kg', 19.78, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('RABLE LAPIN MCX S/OS 2,5KG', 'kg', 21.67, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('LAPIN ENTIER NU +1,4KG', 'kg', 9.89, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('EMINCE LAPIN S/PEAU S/V 1KG', 'kg', 20.29, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CUISSE LAPIN NU 180/220G', 'kg', 17.76, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('RABLE DE LAPIN NU 350 G BBC', 'kg', 17.32, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('RABLE LAPIN NU 300/400G', 'kg', 16.23, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('AIGUILLET,PLT,CORN FLAKES X1KG', 'kg', 14.32, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('NUGGETS VOLAILLE S/ATM 20G X50', 'kg', 8.68, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('AIGUIL,POULET ROTIE 2KG', 'kg', 18.02, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('PAUPIETT DINDE S/F 130/150GX10', 'kg', 14.12, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUCISSE VOLAILLE S/ATM 50GX20', 'kg', 11.29, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FOIE VOLAILLE 1KG', 'kg', 4.77, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('GESIER VOLAILLE S/V 1KG', 'kg', 4.83, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('HACHE VOLAILLE AU COUTEAU 1 KG', 'kg', 11.86, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('KNACK VOLAILLE CUITE 1,2KG HAL', 'kg', 10.12, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('AIGUIL, POULET 2,5 KG HALAL', 'kg', 11.14, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('POULET BLC QRT,ARR, 10KG HALAL', 'kg', 4.98, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('FLT,PLT SP HALAL 120/140GX2,5K', 'kg', 11.02, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FILET POULET S/PEAU HALAL 2,5K', 'kg', 11.02, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF MACREUSE/TT/TG CUIT SV 2,2KG', 'kg', 19.36, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF PALERON CUIT BRAISE SV 2,2KG', 'kg', 18.04, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K PALERON DE BŒUF CONFIT CUIT SV 2KG (dans la graisse de canard)', 'kg', 18.3, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K PALERON DE VEAU CONFIT CUIT SV 1KG (dans la graisse de canard)', 'kg', 19.0, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K PALERON DE VEAU CONFIT CUIT SV 1KG CONGELE', 'kg', 20.89, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE PORC FILET CUIT SV 2,2KG', 'kg', 10.16, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ECHINE DE PORC CONFITE CUITE SV 2KG CONGELE', 'kg', 11.66, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE DINDE FILET CUIT SV 2,2KG', 'kg', 16.02, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('SAUTE DE VEAU 35G CUIT CONGELE', 'kg', 20.75, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('SAUTE DE PORC 35G CUIT CONGELE', 'kg', 11.85, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K FAUX FILET FACON TATAKI VBF 200G PRECUIT MARINE CONGELE', 'kg', 32.1, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K TRANCHE ROTI BŒUF CUIT 20G CONGELE IQF', 'kg', 19.95, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K SOURIS D''AGNEAU CUITE 350g/550G x 1', 'kg', 19.16, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K JARRET DE PORC A LA FLEUR DE BIERE CUIT 380/600G', 'kg', 9.2, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K CHILI CON CARNE CUIT 300G SOUS VIDE CONGELE', 'kg', 13.68, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF JUMEAU CUIT SV 1,4KG', 'kg', 18.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('K FONDANT DE VEAU CUIT (au Pineau des Charentes) SV 1,2KG', 'kg', 18.45, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K NOIX DE JOUE DE BŒUF CUITE CONFITE SV 2KG ENV', 'kg', 17.89, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('K FONDANT DE VEAU CUIT CONFIT SV 1,2KG', 'kg', 17.54, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K NOIX JOUE PORC CUIT CONFIT SV 1KG', 'kg', 13.55, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K EFFILOCHE DE PORC CUIT CONFIT OIGNON-POIVRE 500G SOUS VIDE CONGELE', 'kg', 15.8, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K EFFILOCHE DE PORC CUIT SAVEUR EPICES CAJUN 500G SOUS VIDE FRAIS', 'kg', 14.2, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K BOURGUIGNON BŒUF UE 35G CUIT SV 5KG CONGELE', 'kg', 19.23, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K SAUTE DE VEAU 35G CUIT CONGELE', 'kg', 20.75, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K SAUTE DE PORC 35G CUIT CONGELE', 'kg', 11.85, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF MACREUSE/TT/TG CUIT SV 2,2KG CONGELE', 'pièce', 21.16, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF JUMEAU CUIT SV 1,4KG CONGELE', 'pièce', 19.9, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('K ROTI DE BŒUF PALERON CUIT BRAISE SV 2,2KG CONGELE', 'kg', 19.34, 'Transgourmet', 'Viandes', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;