INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('ORANGE A JUS 6/7 15KG "RG"', 'kg', 1.19, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON BERGAMOTE CAT I ''"CASTAGNARO" COLIS 2,5 KG CAT I', 'kg', 4.89, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ORANGE NAVEL CAT I CAL 3 / COLIS 8.5 KG', 'kg', 2.19, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON BERGAMOTE "LIMONETTE DE MARRAKECH" CAT I', 'kg', 4.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON 4/5 FILET 1KG CAT 1 IMPORT', 'pièce', 2.59, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON CAVIAR JAUNE BQTE 100G', 'pièce', 15.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CITRON CAVIAR ROSE BQTE 100G', 'pièce', 15.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('BANANE P14 18,5KG CAT 1 IMPORT', 'kg', 1.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('BANANE P20 5KG CAT1 IMPORT', 'kg', 1.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FRAISE GARIGUETTE 800G C.1 France', 'pièce', 16.49, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FRAISE GARIQUETTE 250G C.1 FRANCE', 'pièce', 4.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FRAMBOISE 125G CAT 1', 'pièce', 3.29, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FRAMBOISE 125G CAT 1 driscoll', 'pièce', 3.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('MURE 125G CAT 1', 'pièce', 3.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('GROSEILLE 125G CAT 1', 'pièce', 3.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PASTEQUE FASHION S/P 7,5KG CAL 2', 'kg', 3.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('TOMATE CERISE ALLONGEE CAT1 FR.250G', 'pièce', 2.49, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE COTELEE NOIRE CRIMEE CAT2 FR.3,5KG', 'kg', 5.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE ANANAS COTELEE FR.CAT2 3.5KG', 'kg', 5.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE COTELEE MARMANDE CAT2 FR. 3.5KG', 'kg', 5.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE COCKTAIL GRAPPE CAT1 FR. 3.5KG', 'kg', 6.49, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TOMATE CERISE MULTICOLORE CAT1 FR.4KG', 'kg', 6.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('AUBERGINE FILET 1KG', 'kg', 4.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('COURGETTE FILET 1KG', 'kg', 2.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('POIVRON ROUGE 1KG CAT 1 UE', 'kg', 4.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('POIVRON VERT FILET 1KG CAT 1 UE', 'kg', 4.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('POIVRON JAUNE FILET 1KG CAT 1 UE', 'kg', 4.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ASPERGE VIOLETTE 16/22 C.1 France', 'kg', 18.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ASPERGE BLANCHE 500G CAL 16/22 C.1 France', 'kg', 10.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ASPERGE VIOLETTE 16/22 C.1 France', 'kg', 13.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('ASPERGE VERTE 16/22 C.1 France', 'kg', 12.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('AIL DES OURS C.1 France', 'kg', 17.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CEBETTE 100G PROVENCE CAT 1', 'kg', 1.46, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CHOU FLEUR CAT 1', 'pièce', 2.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('POIREAU BOTTE 1KG CAT 1', 'kg', 1.59, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('SALADE CRAQUANTE ITALIENNE CAT 1 500g "MARIUS AUDA"', 'kg', 3.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('SALADE MELANGE NICOIS CAT 1500G "MARIUS AUDA"', 'kg', 3.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('SALADE MELANGE BISTROT CAT 1 500G "MARIUS AUDA"', 'kg', 3.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('PDT AGRIA FRITE 10KG CAT 1 France', 'kg', 0.79, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('PDT SIRTEMANOIRMOUTIER France IGP 35/55', 'kg', 9.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FEUILLE CAPUCINE X15PCE', 'kg', 4.51, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLEUR LAVANDE 30G', 'kg', 3.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLEUR PHLOX', 'kg', 3.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLEUR PENSEE/VIOLA', 'kg', 3.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FLEUR DE FENOUIL', 'kg', 3.95, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('FLEUR MINI BATAILLE', 'kg', 3.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MICRO POUSSE FOLIE DE RADIS France 40G', 'kg', 5.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('MICRO POUSSE CORIANDRE France 30G', 'kg', 5.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MICRO POUSSE POIS VERT France 40G', 'kg', 5.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MICRO POUSSE MELI-MELO France 40G', 'kg', 5.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;