INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('140/160 g', 'kg', 20.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 20.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('80/100 g', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('120 g', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160 g', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pavé de turbot sans peau', 'kg', 115.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Bar entier vidée grattée', 'kg', 14.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Dorade royale vidée grattée', 'kg', 16.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Tronçon de turbot', 'kg', 90.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('60/80 g', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('110/130 g', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/160 g', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/200 g', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Anneaux d''encornet décongelées saumurées', 'kg', 15.3, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('Lamelle d''encornet décongelées saumurées', 'kg', 9.99, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('Tentacules de calamar décongelées saumurées', 'kg', 9.9, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('Amandes de mer', 'kg', 4.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Bulot cuit', 'kg', 10.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Corail d''oursin pasteurisé', 'kg', 23.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Coques', 'kg', 10.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Couteau', 'kg', 9.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('20/30', 'kg', 10.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('30/50', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('30/50', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('40/60', 'kg', 8.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('40/60', 'kg', 8.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('60/80', 'kg', 7.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('60/80', 'kg', 7.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Crevette grise moyenne', 'kg', 21.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Crevette grise décortiquée', 'kg', 8.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Crevette grise jumbo', 'kg', 23.95, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Crevette cuite LABEL ROUGE', 'kg', 33.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Chair de tourteaux', 'kg', 75.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Huitre fine normande n°3', 'kg', 30.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Huitre fine normande n°2', 'kg', 35.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 50.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 54.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 62.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 64.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('10/15', 'kg', 29.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('16/20', 'kg', 23.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Bq s/at de 2 kg', 'kg', 3.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Au sac de 10 kg', 'kg', 3.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Moule Hollande PAC BIO', 'kg', 8.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Moule décortiquée', 'kg', 18.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Noix St Jacques avec corail Normande', 'kg', 37.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Noix St jacques avec corail Ecosse', 'kg', 29.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Noix St jacques avec corail Normande', 'kg', 35.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Préparation noix de saint jacques décongelée', 'kg', 55.9, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;