INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('Tourteau cuit sous vide', 'pièce', 18.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine de Langoustines', 'kg', 19.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine de Saint-Jacques au muscadet', 'kg', 15.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine de Crabe Armoricaine', 'kg', 26.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine du Pêcheur', 'kg', 14.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Terrine de Homard au Cognac', 'kg', 23.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Cocktail de fruits de mer en saumure', 'kg', 13.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('120 g', 'kg', 9.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Fish and Chips de Colin', 'kg', 12.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de colin meunière', 'kg', 13.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Brandade de morue parmentière', 'kg', 6.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Caviar Oscietre', 'kg', 67.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Caviar Aquitaine Baeri', 'kg', 68.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Poulpe pour carpaccio', 'kg', 70.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Poulpe entier cuit', 'kg', 43.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Tentacule de poulpe cuit', 'kg', 47.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Marinade de pouple', 'kg', 42.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Marinade de calamars', 'kg', 35.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de bonite melva canutera à l''huile d''olive', 'kg', 7.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de Haddock fumé', 'kg', 36.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Chute de haddock fumé', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de hareng doux fumé JC DAVID Label Rouge', 'kg', 4.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filets de hareng fumé', 'kg', 10.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de truite fumé sans arrête tranché machine', 'pièce', 37.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Morue salée', 'kg', 19.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Miettes de morue salée', 'kg', 18.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Miette de surimi', 'kg', 4.1, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Rouleau de surimi SMC', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Jus de moule', 'kg', 5.4, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de 500 g', 'kg', 7.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Tarama blanc', 'kg', 16.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Tarama truffe d''été', 'kg', 11.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de 500 g', 'kg', 11.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de 300g', 'kg', 43.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Œuf de saumon sauvage', 'kg', 13.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Œuf de lompe rouge', 'kg', 5.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Œuf de lompe noir', 'kg', 5.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Œufs de poisson volant wazabi décongelé', 'kg', 8.5, 'Transgourmet', 'Surgelés', 5, 8, NOW(), NOW()),
('Œuf truite', 'kg', 36.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Œuf truite', 'kg', 10.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Œufs de brochet', 'kg', 10.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Poutargue classique sans cire', 'kg', 118.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Poutargue fumée sans cire', 'kg', 119.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de crevettes moyenne en saumure', 'kg', 16.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de crevettes moyenne en saumure', 'kg', 16.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de crevettes grosse en saumure', 'kg', 17.0, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pot de chair de crabe ordinaire', 'kg', 14.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Pot de queue d''écrevisses de Louisiane en saumure', 'kg', 30.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Rillettes de maquereau fumé au poivre', 'kg', 4.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Sardines à l''huile d''olive vierge extra BIO millésimées', 'kg', 5.4, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;