INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "supplierId", "createdAt", "updatedAt") VALUES
('MICRO POUSSE MOUTARDE France 40G', 'kg', 5.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('MICRO POUSSE RADIS POURPRE France 40G', 'kg', 5.99, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('TRUFFE FRAICHE HIVER 3/4 PIECES CAT 1 100G FR', 'kg', 290.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('TRUFFE FRAICHE HIVER 1/2 PIECES CAT 1 100G FR', 'kg', 290.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('TRUFFE FRAICHE HIVER 8/10 PIECES CAT 1 100G FR', 'kg', 250.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('COFFRET TRUFFE HIVER 1P EXTRA 100G + RAPE + BROSSE', 'kg', 149.0, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('FRUIT DE LA PASSION CAT1 1KG', 'kg', 15.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ANANAS B9 CAT2 *BIO', 'kg', 3.49, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BASILIC PETIT POT X6 CAT2 FR.*BIO', 'kg', 1.79, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('BATAVIA X12 CAT2 FR.3.6KG *BIO', 'kg', 16.8, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CELERI RAVE FR.X8 8KG CAT2*BIO', 'kg', 2.79, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('CHOU BLANC CAT2 FR.1KG *BIO', 'kg', 2.29, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('MANDARINE 3/4 CAT2 6KG *BIO', 'kg', 2.99, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('CONCOMBRE 3/4 CAT2 *BIO', 'kg', 24.0, 'Transgourmet', 'Fruits & Légumes', 5, 8, NOW(), NOW()),
('PDT MAIWEN BROSSEE 40/60 FR.10KG CAT2 *BIO X', 'kg', 1.89, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('PERSIL FRISE PETIT POT X6 FR.CAT2 BIO', 'kg', 1.79, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('ROMARIN PETIT POT CAT2 FR.(6) *BIO', 'kg', 1.79, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('THYM PETIT POT X6 FR.CAT2 *BIO', 'kg', 1.79, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1.5/1.9 kg', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de saumon sans peau sans arrêtes ASC', 'kg', 24.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('120 g', 'kg', 23.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('150 g', 'kg', 23.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180 g', 'kg', 23.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('90 g', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('120 g', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('150 g', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180 g', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('4/5 kg', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('2/3 kg', 'kg', 14.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Truite entière vidée grattée', 'kg', 12.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Truite portion vidée', 'kg', 11.3, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 20.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de truite avec peau sans arêtes', 'kg', 12.95, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Pavé de truite avec peau', 'kg', 26.9, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Huître Marennes Oléron n°2 IGP', 'kg', 42.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Huître Marennes Oléron n°3 IGP', 'kg', 36.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Huître Marennes Oléron n°3 IGP', 'kg', 66.3, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de dorade', 'kg', 28.5, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 16.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 18.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('140/180 g', 'kg', 32.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('180/220 g', 'kg', 37.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('400/600 g', 'kg', 15.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('600/800 g', 'kg', 17.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('800g/1 kg', 'kg', 19.5, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('1/1,5 kg', 'kg', 22.2, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de harend doux Label Rouge', 'kg', 15.9, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Filet de haddock moyen fumé à l''ancienne MSC', 'kg', 36.95, 'Transgourmet', 'Épicerie', 5, 8, NOW(), NOW()),
('Dos cabillaud avec peau', 'kg', 36.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW()),
('Dos cabillaud sans peau', 'kg', 31.99, 'Transgourmet', 'Poissons', 5, 8, NOW(), NOW())
ON CONFLICT DO NOTHING;