INSERT INTO ingredients (name, unit, "pricePerUnit", supplier, category, "restaurantId", "createdAt", "updatedAt") VALUES
('> Le Duo Haché façon bouchère VBF 100g et 140g > à partir de', 'kg', 1.25, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
(',11 €', 'kg', 171.11, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
(',89 €', 'kg', 159.89, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('-13,2%', 'kg', 12.64, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('-11,8%', 'kg', 17.19, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('-10,0%', 'kg', 20.57, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Code : 214137', 'kg', 3.38, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('de 250 g', 'kg', 1.08, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('de 140 g', 'kg', 1.94, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('de 150 g', 'kg', 1.28, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('de 350 g', 'kg', 1.83, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('le kilo', 'kg', 14.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Code : 300940', 'kg', 1.68, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Code : 231499', 'kg', 6.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Code : 967689', 'kg', 2.39, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Code : 818543', 'kg', 1.15, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Code : 572307', 'kg', 12.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('À MOINS DE', 'kg', 1.95, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('PRIX/PORTION DE REVIENT HT', 'kg', 0.16, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pomme de terre grenaille (120 g) - Code 300940', 'kg', 1.68, 'Transgourmet', 'Fruits & Légumes', 5, NOW(), NOW()),
('Romarin frais, beurre, huile d’olive, sel et poivre', 'kg', 0.25, 'Transgourmet', 'Produits laitiers', 5, NOW(), NOW()),
('Pomme de terre grenaille (180 g) - Code 300940', 'kg', 1.28, 'Transgourmet', 'Fruits & Légumes', 5, NOW(), NOW()),
('Huile d ’olive Economy, Ail, Thym, Chimichurri', 'kg', 0.57, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Panais (120 g) - Code 422775', 'kg', 1.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('0,160 € HT', 'kg', 1.33, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Carottes, Huile Olive Economy, Crème 18% Quality, Emmental Economy', 'kg', 0.26, 'Transgourmet', 'Fruits & Légumes', 5, NOW(), NOW()),
('Asperges vertes (80 g) - Code 572307', 'kg', 1.46, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Aneth fraîche, huile d’olive, citron, sel et poivre', 'kg', 0.35, 'Transgourmet', 'Fruits & Légumes', 5, NOW(), NOW()),
('SACHET', 'sachet', 3.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
(',00 €', 'kg', 149.0, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('1.5/1.9 kg', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Bq s/at par 20 pièces', 'kg', 24.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('4/5 kg', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('2/3 kg', 'kg', 14.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Bq s/at par 5 pièces', 'kg', 12.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('A la caisse de 6 kg', 'kg', 11.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('France', 'kg', 5.4, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Bourriche de 48', 'kg', 36.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Bourriche de 96', 'kg', 66.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Barquette de 10 pièces France', 'kg', 28.5, 'Transgourmet', 'Poissons', 5, NOW(), NOW()),
('/600 g', 'kg', 15.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/800 g', 'kg', 13.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/180 g', 'kg', 32.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/220 g', 'kg', 37.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('g/1 kg', 'kg', 19.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('1/1,5 kg', 'kg', 22.2, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Sachet de 1 kg', 'sachet', 15.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse de bois', 'kg', 36.95, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Atlantique Nord Est', 'kg', 4.0, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse 3kg', 'kg', 12.2, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse de 5 kg', 'kg', 14.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse de 3 kg', 'kg', 9.0, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('3/4 kg', 'kg', 12.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('2,75 kg', 'kg', 26.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse de 6 kg', 'kg', 13.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pièce de 1/2 kg', 'kg', 31.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pièce de 2/3 kg', 'kg', 39.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Méditerranée', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('4/6 kg', 'kg', 20.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('2/4 kg', 'kg', 16.6, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/1000 g', 'kg', 14.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Estonie', 'kg', 21.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/400 g', 'kg', 14.2, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/500 g', 'kg', 29.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse de 4', 'kg', 14.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('s/vide par 1 pièce', 'kg', 18.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse de 10 kg', 'kg', 16.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse 5kg', 'kg', 16.1, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse 2kg', 'kg', 22.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Espagne/Croatie/Egypte', 'kg', 32.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Caisse 6kg', 'kg', 16.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('A la pièce', 'kg', 25.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Grèce / Turquie / Espagne', 'kg', 14.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/500G', 'kg', 29.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('5/6 kg', 'kg', 12.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('6/7 kg', 'kg', 12.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('7/8 kg', 'kg', 12.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Ecosse', 'kg', 15.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Hollande', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('1/2 kg', 'kg', 24.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/160 g', 'kg', 20.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/200 g', 'kg', 20.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/160g', 'kg', 22.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('/130 g', 'kg', 25.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Bq s/at par 10 pièces', 'kg', 23.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Croatie', 'kg', 32.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Norvège', 'kg', 20.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Espagne', 'kg', 7.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
(',90 €', 'kg', 115.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Anneaux d''encornet décongelées saumurées', 'kg', 15.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Lamelle d''encornet décongelées saumurées', 'kg', 9.99, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Par 6 pots', 'kg', 23.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Madagascar', 'kg', 33.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Canada', 'kg', 50.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Bq s/at de 2 kg', 'kg', 3.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Au sac de 10 kg', 'kg', 3.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Danemark, Pays-Bas', 'kg', 18.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('U.S.A.', 'kg', 55.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Irlande', 'kg', 18.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Terrine de Langoustines', 'kg', 19.0, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Terrine de Saint-Jacques au muscadet', 'kg', 15.95, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Terrine de Crabe Armoricaine', 'kg', 26.0, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Terrine du Pêcheur', 'kg', 14.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Terrine de Homard au Cognac', 'kg', 23.3, 'Transgourmet', 'Poissons', 5, NOW(), NOW()),
('Pot de 1,5 kg', 'kg', 13.0, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pacifique Nord Est', 'kg', 9.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Bq s/at par 8 pièces', 'kg', 12.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Transformée en France', 'kg', 6.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pologne', 'kg', 67.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Rouleau de 600 g', 'kg', 70.0, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('A la pièce de 300/500 g', 'kg', 43.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('A la pièce de 100/150 g', 'kg', 47.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pièce de 2 kg', 'kg', 35.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Lituanie', 'kg', 4.1, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Islande', 'kg', 7.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pot de 1 kg', 'kg', 16.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pot de 300g', 'kg', 43.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pot de 100 g', 'kg', 5.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Belgique', 'kg', 10.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pot de 50g', 'kg', 10.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Atlantique Centre Est', 'kg', 118.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
(',50 €', 'kg', 118.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pot de 900 g', 'kg', 16.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Elevé en France', 'kg', 14.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pêchée en eau douce Chine', 'kg', 30.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Iles Féroé', 'kg', 44.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Boîte de 975 g', 'kg', 28.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Pot de 780 g', 'kg', 5.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('BRETAGNE', 'kg', 8.5, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Portugal', 'kg', 15.3, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Colis de 50', 'kg', 8.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Boîte de 500 g', 'kg', 12.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Paquet de 200 g', 'kg', 2.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW()),
('Paquet de 135 g', 'kg', 2.9, 'Transgourmet', 'Épicerie', 5, NOW(), NOW());