const { PrismaClient } = require('../node_modules/@prisma/client');
const prisma = new PrismaClient();

const newIngredients = [
  // VIANDES
  {name:"Entrecôte de boeuf",unit:"kg",pricePerUnit:22,category:"Viandes"},
  {name:"Faux-filet de boeuf",unit:"kg",pricePerUnit:20,category:"Viandes"},
  {name:"Filet de boeuf",unit:"kg",pricePerUnit:42,category:"Viandes"},
  {name:"Onglet de boeuf",unit:"kg",pricePerUnit:18,category:"Viandes"},
  {name:"Rumsteck",unit:"kg",pricePerUnit:16,category:"Viandes"},
  {name:"Paleron de boeuf",unit:"kg",pricePerUnit:12,category:"Viandes"},
  {name:"Joue de boeuf",unit:"kg",pricePerUnit:13,category:"Viandes"},
  {name:"Côte de boeuf",unit:"kg",pricePerUnit:25,category:"Viandes"},
  {name:"Steak haché pur boeuf",unit:"kg",pricePerUnit:11,category:"Viandes"},
  {name:"Carpaccio de boeuf",unit:"kg",pricePerUnit:22,category:"Viandes"},
  {name:"Tartare de boeuf",unit:"kg",pricePerUnit:20,category:"Viandes"},
  {name:"Os à moelle",unit:"kg",pricePerUnit:5,category:"Viandes"},
  {name:"Rôti de veau",unit:"kg",pricePerUnit:23,category:"Viandes"},
  {name:"Ris de veau",unit:"kg",pricePerUnit:40,category:"Viandes"},
  {name:"Foie de veau",unit:"kg",pricePerUnit:20,category:"Viandes"},
  {name:"Jarret de veau",unit:"kg",pricePerUnit:14,category:"Viandes"},
  {name:"Osso buco",unit:"kg",pricePerUnit:15,category:"Viandes"},
  {name:"Carré d'agneau",unit:"kg",pricePerUnit:24,category:"Viandes"},
  {name:"Gigot d'agneau",unit:"kg",pricePerUnit:18,category:"Viandes"},
  {name:"Épaule d'agneau",unit:"kg",pricePerUnit:14,category:"Viandes"},
  {name:"Côtelettes d'agneau",unit:"kg",pricePerUnit:22,category:"Viandes"},
  {name:"Merguez",unit:"kg",pricePerUnit:9,category:"Viandes"},
  {name:"Filet mignon de porc",unit:"kg",pricePerUnit:11,category:"Viandes"},
  {name:"Travers de porc",unit:"kg",pricePerUnit:8,category:"Viandes"},
  {name:"Épaule de porc",unit:"kg",pricePerUnit:6,category:"Viandes"},
  {name:"Poitrine de porc",unit:"kg",pricePerUnit:7,category:"Viandes"},
  {name:"Jambon blanc",unit:"kg",pricePerUnit:9,category:"Viandes"},
  {name:"Jambon cru",unit:"kg",pricePerUnit:18,category:"Viandes"},
  {name:"Saucisse de Toulouse",unit:"kg",pricePerUnit:9,category:"Viandes"},
  {name:"Chipolatas",unit:"kg",pricePerUnit:8,category:"Viandes"},
  {name:"Andouillette",unit:"kg",pricePerUnit:10,category:"Viandes"},
  {name:"Boudin noir",unit:"kg",pricePerUnit:8,category:"Viandes"},
  {name:"Poulet entier fermier",unit:"kg",pricePerUnit:10,category:"Viandes"},
  {name:"Foie gras de canard cru",unit:"kg",pricePerUnit:45,category:"Viandes"},
  {name:"Dinde escalope",unit:"kg",pricePerUnit:9,category:"Viandes"},
  {name:"Pintade",unit:"kg",pricePerUnit:12,category:"Viandes"},
  {name:"Caille",unit:"pièce",pricePerUnit:3.5,category:"Viandes"},
  {name:"Lapin entier",unit:"kg",pricePerUnit:10,category:"Viandes"},
  {name:"Queue de boeuf",unit:"kg",pricePerUnit:11,category:"Viandes"},
  {name:"Saucisson sec",unit:"kg",pricePerUnit:14,category:"Viandes"},
  {name:"Coppa",unit:"kg",pricePerUnit:18,category:"Viandes"},
  {name:"Bresaola",unit:"kg",pricePerUnit:25,category:"Viandes"},
  {name:"Pancetta",unit:"kg",pricePerUnit:14,category:"Viandes"},
  {name:"Chorizo",unit:"kg",pricePerUnit:10,category:"Viandes"},
  {name:"Rillettes de canard",unit:"kg",pricePerUnit:16,category:"Viandes"},
  {name:"Pâté de campagne",unit:"kg",pricePerUnit:8,category:"Viandes"},
  {name:"Terrine de foie gras",unit:"kg",pricePerUnit:50,category:"Viandes"},
  // POISSONS
  {name:"Saumon fumé",unit:"kg",pricePerUnit:30,category:"Poissons & Fruits de mer"},
  {name:"Dorade filet",unit:"kg",pricePerUnit:22,category:"Poissons & Fruits de mer"},
  {name:"Truite filet",unit:"kg",pricePerUnit:14,category:"Poissons & Fruits de mer"},
  {name:"Lieu noir filet",unit:"kg",pricePerUnit:12,category:"Poissons & Fruits de mer"},
  {name:"Merlu filet",unit:"kg",pricePerUnit:14,category:"Poissons & Fruits de mer"},
  {name:"Maquereau",unit:"kg",pricePerUnit:6,category:"Poissons & Fruits de mer"},
  {name:"Sardines fraîches",unit:"kg",pricePerUnit:7,category:"Poissons & Fruits de mer"},
  {name:"Gambas crues",unit:"kg",pricePerUnit:18,category:"Poissons & Fruits de mer"},
  {name:"Langoustines",unit:"kg",pricePerUnit:30,category:"Poissons & Fruits de mer"},
  {name:"Homard",unit:"kg",pricePerUnit:35,category:"Poissons & Fruits de mer"},
  {name:"Huîtres n3",unit:"douzaine",pricePerUnit:9,category:"Poissons & Fruits de mer"},
  {name:"Calamars",unit:"kg",pricePerUnit:10,category:"Poissons & Fruits de mer"},
  {name:"Poulpe",unit:"kg",pricePerUnit:12,category:"Poissons & Fruits de mer"},
  {name:"Lotte queue",unit:"kg",pricePerUnit:25,category:"Poissons & Fruits de mer"},
  {name:"Rouget filet",unit:"kg",pricePerUnit:20,category:"Poissons & Fruits de mer"},
  {name:"Turbot",unit:"kg",pricePerUnit:30,category:"Poissons & Fruits de mer"},
  // LÉGUMES
  {name:"Tomate grappe",unit:"kg",pricePerUnit:2.5,category:"Légumes"},
  {name:"Tomate cerise",unit:"kg",pricePerUnit:5,category:"Légumes"},
  {name:"Tomate coeur de boeuf",unit:"kg",pricePerUnit:5,category:"Légumes"},
  {name:"Pomme de terre grenaille",unit:"kg",pricePerUnit:2.5,category:"Légumes"},
  {name:"Pomme de terre Ratte",unit:"kg",pricePerUnit:4,category:"Légumes"},
  {name:"Oignon rouge",unit:"kg",pricePerUnit:1.5,category:"Légumes"},
  {name:"Carotte fane",unit:"botte",pricePerUnit:2.5,category:"Légumes"},
  {name:"Navet",unit:"kg",pricePerUnit:1.8,category:"Légumes"},
  {name:"Fenouil",unit:"kg",pricePerUnit:3,category:"Légumes"},
  {name:"Asperges blanches",unit:"kg",pricePerUnit:12,category:"Légumes"},
  {name:"Cèpes frais",unit:"kg",pricePerUnit:40,category:"Légumes"},
  {name:"Girolles",unit:"kg",pricePerUnit:30,category:"Légumes"},
  {name:"Pleurotes",unit:"kg",pricePerUnit:8,category:"Légumes"},
  {name:"Shiitake",unit:"kg",pricePerUnit:12,category:"Légumes"},
  {name:"Panais",unit:"kg",pricePerUnit:3.5,category:"Légumes"},
  {name:"Topinambour",unit:"kg",pricePerUnit:5,category:"Légumes"},
  {name:"Patate douce",unit:"kg",pricePerUnit:3,category:"Légumes"},
  {name:"Radis",unit:"botte",pricePerUnit:1,category:"Légumes"},
  {name:"Chou rouge",unit:"kg",pricePerUnit:1.5,category:"Légumes"},
  {name:"Chou vert",unit:"kg",pricePerUnit:1.2,category:"Légumes"},
  {name:"Petits pois frais",unit:"kg",pricePerUnit:6,category:"Légumes"},
  {name:"Gingembre frais",unit:"kg",pricePerUnit:6,category:"Légumes"},
  {name:"Piment frais",unit:"kg",pricePerUnit:8,category:"Légumes"},
  {name:"Endive",unit:"kg",pricePerUnit:3,category:"Légumes"},
  {name:"Cresson",unit:"botte",pricePerUnit:2,category:"Légumes"},
  {name:"Blette",unit:"kg",pricePerUnit:2.5,category:"Légumes"},
  {name:"Courge butternut",unit:"kg",pricePerUnit:2,category:"Légumes"},
  {name:"Potimarron",unit:"kg",pricePerUnit:2.5,category:"Légumes"},
  // FRUITS
  {name:"Framboise",unit:"kg",pricePerUnit:18,category:"Fruits"},
  {name:"Myrtille",unit:"kg",pricePerUnit:16,category:"Fruits"},
  {name:"Mangue",unit:"pièce",pricePerUnit:2.5,category:"Fruits"},
  {name:"Ananas",unit:"pièce",pricePerUnit:2.5,category:"Fruits"},
  {name:"Melon",unit:"pièce",pricePerUnit:3.5,category:"Fruits"},
  {name:"Pastèque",unit:"kg",pricePerUnit:1.5,category:"Fruits"},
  {name:"Raisin",unit:"kg",pricePerUnit:3.5,category:"Fruits"},
  {name:"Pêche",unit:"kg",pricePerUnit:3.5,category:"Fruits"},
  {name:"Abricot frais",unit:"kg",pricePerUnit:5,category:"Fruits"},
  {name:"Figue fraîche",unit:"kg",pricePerUnit:10,category:"Fruits"},
  {name:"Fruit de la passion",unit:"kg",pricePerUnit:14,category:"Fruits"},
  {name:"Kiwi",unit:"kg",pricePerUnit:3,category:"Fruits"},
  {name:"Cerise",unit:"kg",pricePerUnit:8,category:"Fruits"},
  {name:"Rhubarbe",unit:"kg",pricePerUnit:4,category:"Fruits"},
  {name:"Clémentine",unit:"kg",pricePerUnit:2.5,category:"Fruits"},
  {name:"Pamplemousse",unit:"pièce",pricePerUnit:1,category:"Fruits"},
  // PRODUITS LAITIERS
  {name:"Crème fraîche épaisse 30%",unit:"L",pricePerUnit:4,category:"Produits laitiers"},
  {name:"Lait entier",unit:"L",pricePerUnit:1,category:"Produits laitiers"},
  {name:"Lait demi-écrémé",unit:"L",pricePerUnit:0.9,category:"Produits laitiers"},
  {name:"Gruyère IGP",unit:"kg",pricePerUnit:14,category:"Produits laitiers"},
  {name:"Comté AOP",unit:"kg",pricePerUnit:18,category:"Produits laitiers"},
  {name:"Mozzarella di Bufala",unit:"kg",pricePerUnit:16,category:"Produits laitiers"},
  {name:"Burrata",unit:"pièce",pricePerUnit:3.5,category:"Produits laitiers"},
  {name:"Camembert AOP",unit:"pièce",pricePerUnit:3,category:"Produits laitiers"},
  {name:"Brie de Meaux",unit:"kg",pricePerUnit:12,category:"Produits laitiers"},
  {name:"Mascarpone",unit:"kg",pricePerUnit:6,category:"Produits laitiers"},
  {name:"Ricotta",unit:"kg",pricePerUnit:6,category:"Produits laitiers"},
  {name:"Yaourt nature",unit:"kg",pricePerUnit:2.5,category:"Produits laitiers"},
  {name:"Fromage blanc",unit:"kg",pricePerUnit:3,category:"Produits laitiers"},
  {name:"Oeufs plein air",unit:"pièce",pricePerUnit:0.30,category:"Produits laitiers"},
  {name:"Lait de coco",unit:"L",pricePerUnit:3,category:"Produits laitiers"},
  // ÉPICERIE
  {name:"Vinaigre balsamique",unit:"L",pricePerUnit:8,category:"Épicerie"},
  {name:"Sauce soja",unit:"L",pricePerUnit:4,category:"Épicerie"},
  {name:"Worcestershire sauce",unit:"L",pricePerUnit:8,category:"Épicerie"},
  {name:"Tabasco",unit:"L",pricePerUnit:22,category:"Épicerie"},
  {name:"Concentré de tomate",unit:"kg",pricePerUnit:3.5,category:"Épicerie"},
  {name:"Tomates concassées conserve",unit:"kg",pricePerUnit:1.2,category:"Épicerie"},
  {name:"Coulis de tomate",unit:"L",pricePerUnit:2.5,category:"Épicerie"},
  {name:"Olives noires",unit:"kg",pricePerUnit:6,category:"Épicerie"},
  {name:"Olives vertes",unit:"kg",pricePerUnit:5,category:"Épicerie"},
  {name:"Câpres",unit:"kg",pricePerUnit:12,category:"Épicerie"},
  {name:"Cornichons",unit:"kg",pricePerUnit:5,category:"Épicerie"},
  {name:"Riz arborio risotto",unit:"kg",pricePerUnit:3.5,category:"Épicerie"},
  {name:"Pâtes penne",unit:"kg",pricePerUnit:1.8,category:"Épicerie"},
  {name:"Pâtes tagliatelles fraîches",unit:"kg",pricePerUnit:5,category:"Épicerie"},
  {name:"Couscous semoule",unit:"kg",pricePerUnit:1.5,category:"Épicerie"},
  {name:"Haricots blancs secs",unit:"kg",pricePerUnit:3,category:"Épicerie"},
  {name:"Sucre en poudre",unit:"kg",pricePerUnit:1,category:"Épicerie"},
  {name:"Sucre glace",unit:"kg",pricePerUnit:1.5,category:"Épicerie"},
  {name:"Sel de Guérande",unit:"kg",pricePerUnit:4,category:"Épicerie"},
  {name:"Miel",unit:"kg",pricePerUnit:9,category:"Épicerie"},
  {name:"Confiture abricot",unit:"kg",pricePerUnit:5,category:"Épicerie"},
  {name:"Pâte de curry",unit:"kg",pricePerUnit:12,category:"Épicerie"},
  {name:"Harissa",unit:"kg",pricePerUnit:8,category:"Épicerie"},
  {name:"Nuoc-mâm",unit:"L",pricePerUnit:5,category:"Épicerie"},
  {name:"Chapelure",unit:"kg",pricePerUnit:2,category:"Épicerie"},
  {name:"Gélatine feuilles",unit:"kg",pricePerUnit:30,category:"Épicerie"},
  // ÉPICES
  {name:"Curcuma moulu",unit:"kg",pricePerUnit:12,category:"Épices & Condiments"},
  {name:"Piment d'Espelette",unit:"kg",pricePerUnit:45,category:"Épices & Condiments"},
  {name:"Ras el hanout",unit:"kg",pricePerUnit:15,category:"Épices & Condiments"},
  {name:"Quatre-épices",unit:"kg",pricePerUnit:14,category:"Épices & Condiments"},
  {name:"Muscade moulue",unit:"kg",pricePerUnit:22,category:"Épices & Condiments"},
  {name:"Cannelle moulue",unit:"kg",pricePerUnit:14,category:"Épices & Condiments"},
  {name:"Gingembre moulu",unit:"kg",pricePerUnit:12,category:"Épices & Condiments"},
  {name:"Safran",unit:"g",pricePerUnit:8,category:"Épices & Condiments"},
  {name:"Piment de Cayenne",unit:"kg",pricePerUnit:14,category:"Épices & Condiments"},
  {name:"Herbes de Provence",unit:"kg",pricePerUnit:10,category:"Épices & Condiments"},
  {name:"Origan séché",unit:"kg",pricePerUnit:12,category:"Épices & Condiments"},
  {name:"Sauge fraîche",unit:"botte",pricePerUnit:1.5,category:"Épices & Condiments"},
  {name:"Laurier feuilles",unit:"kg",pricePerUnit:18,category:"Épices & Condiments"},
  {name:"Citronnelle",unit:"botte",pricePerUnit:2,category:"Épices & Condiments"},
  {name:"Fleur de sel",unit:"kg",pricePerUnit:8,category:"Épices & Condiments"},
  {name:"Poivre de Sichuan",unit:"kg",pricePerUnit:30,category:"Épices & Condiments"},
  {name:"Baies roses",unit:"kg",pricePerUnit:25,category:"Épices & Condiments"},
  {name:"Sumac",unit:"kg",pricePerUnit:18,category:"Épices & Condiments"},
  {name:"Zaatar",unit:"kg",pricePerUnit:15,category:"Épices & Condiments"},
  // FONDS
  {name:"Demi-glace",unit:"L",pricePerUnit:8,category:"Fonds & Bouillons"},
  {name:"Bouillon de boeuf",unit:"L",pricePerUnit:4,category:"Fonds & Bouillons"},
  {name:"Bouillon de légumes",unit:"L",pricePerUnit:3,category:"Fonds & Bouillons"},
  {name:"Jus de viande",unit:"L",pricePerUnit:6,category:"Fonds & Bouillons"},
  // BOISSONS
  {name:"Vin blanc sec cuisine",unit:"L",pricePerUnit:5,category:"Boissons"},
  {name:"Vin rosé",unit:"L",pricePerUnit:5,category:"Boissons"},
  {name:"Bière blonde",unit:"L",pricePerUnit:3,category:"Boissons"},
  {name:"Cidre brut",unit:"L",pricePerUnit:3.5,category:"Boissons"},
  {name:"Jus d'orange pur jus",unit:"L",pricePerUnit:2.5,category:"Boissons"},
  {name:"Eau minérale",unit:"L",pricePerUnit:0.4,category:"Boissons"},
  {name:"Eau gazeuse",unit:"L",pricePerUnit:0.5,category:"Boissons"},
  {name:"Sirop de grenadine",unit:"L",pricePerUnit:3,category:"Boissons"},
  {name:"Café en grain",unit:"kg",pricePerUnit:15,category:"Boissons"},
  {name:"Thé vrac",unit:"kg",pricePerUnit:20,category:"Boissons"},
  {name:"Amaretto",unit:"L",pricePerUnit:12,category:"Boissons"},
  {name:"Pastis",unit:"L",pricePerUnit:15,category:"Boissons"},
  {name:"Vodka",unit:"L",pricePerUnit:12,category:"Boissons"},
  {name:"Whisky",unit:"L",pricePerUnit:18,category:"Boissons"},
  // SURGELÉS
  {name:"Framboises surgelées",unit:"kg",pricePerUnit:8,category:"Surgelés"},
  {name:"Mangue surgelée",unit:"kg",pricePerUnit:6,category:"Surgelés"},
  {name:"Épinards surgelés",unit:"kg",pricePerUnit:2.5,category:"Surgelés"},
  {name:"Haricots verts surgelés",unit:"kg",pricePerUnit:2.5,category:"Surgelés"},
  {name:"Légumes grillés surgelés",unit:"kg",pricePerUnit:4,category:"Surgelés"},
  {name:"Crevettes surgelées",unit:"kg",pricePerUnit:12,category:"Surgelés"},
  {name:"Pâte brisée surgelée",unit:"kg",pricePerUnit:4,category:"Surgelés"},
];

async function main() {
  const existing = await prisma.ingredient.findMany({ select: { name: true } });
  const existingNames = new Set(existing.map(i => i.name.toLowerCase()));
  const toInsert = newIngredients.filter(i => !existingNames.has(i.name.toLowerCase()));
  console.log('To insert:', toInsert.length, '/', newIngredients.length);

  if (toInsert.length > 0) {
    await prisma.ingredient.createMany({
      data: toInsert.map(i => ({ ...i, allergens: [] })),
      skipDuplicates: true,
    });
  }

  const total = await prisma.ingredient.count();
  console.log('Total ingredients:', total);
  const cats = await prisma.$queryRaw`SELECT category, COUNT(*)::int as cnt FROM ingredients GROUP BY category ORDER BY cnt DESC`;
  cats.forEach(c => console.log('  ' + c.category + ': ' + c.cnt));
  await prisma.$disconnect();
}
main();
