-- =====================================================
-- Migration: 20260425_3010_user_mfa
-- Purpose : Add TOTP MFA fields to the users table (Wave 3 security).
--           totpSecret stores the encrypted base32 secret generated by otplib.
--           totpEnabled is false until the user completes POST /api/auth/mfa/verify.
--
-- Idempotent: both ADD COLUMN use IF NOT EXISTS so safe to re-run.
-- =====================================================

ALTER TABLE users ADD COLUMN IF NOT EXISTS "totpSecret" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "totpEnabled" BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN users."totpSecret"  IS 'TOTP base32 secret (otplib). NULL = MFA not configured. Store encrypted at rest via Supabase column encryption when available.';
COMMENT ON COLUMN users."totpEnabled" IS 'true once user has completed TOTP setup flow (verified first code). Guards login second-factor check.';
